name: Code Review


on:
  pull_request:
    branches:
      - "**"
    paths:
      - "!(library/**)"
      - "**.php"


permissions:
  contents: write
  pull-requests: write


jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@v3
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          SKIP_FOLDERS: "library,.github,wdm-automatic-credit-card-customization/vendor"
          PHPCS_SNIFFS_EXCLUDE: "*.css,*.js"
        with:
          args: "WordPress,WordPress-Core,WordPress-Docs"
